/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [id]
      ,[HookLoad]
      ,[Spp]
      ,[TDtorque]
      ,[RpmHydraulic]
      ,[Mudtemptowell]
      ,[Mudtempfromwell]
      ,[wellheadpress]
      ,[returnmudflow]
      ,[Rop]
      ,[WOB]
      ,[blockpos]
      ,[Tank1]
      ,[Tank2]
      ,[Tank3]
      ,[datatime]
  FROM [software].[dbo].[Well]